import React from 'react'
import { useNavigate } from 'react-router-dom'

export default function Domore() {
  const navigate=useNavigate(); 
  return (
    <div style={{color: "blue",marginTop: "170px"}} className='doo'>
       <h1>DO MORE, BE MORE</h1>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <p>In the modern world, technology has become an integral part of our daily lives. From smartphones that keep us connected to the internet to advanced medical devices that save lives, technology has revolutionized the way we live, work, and communicate. The rapid pace of technological advancement has led to increased convenience and efficiency in many aspects of life. However, it has also brought about new challenges and considerations. One of the most transformative technologies is artificial intelligence (AI). AI is now used in various industries, from healthcare to finance and transportation. It can analyze vast amounts of data, make predictions, and even perform tasks that were once only possible for humans. While AI offers incredible opportunities, it also raises ethical and privacy concerns. The responsible development and use of AI is an ongoing debate.</p>
       <br/>
       <button onClick={()=>navigate(-1)}>Go Back</button>
    </div>
  )
}
